export enum paths {
  HOMEPAGE = "home",
  STREAM_SELECT = "streams",
  EXAMS = "exams",
  COMMUNITY_EXAMS = "community-exams",
  DISCRIPTIVE = "descriptive",
  MCQ = "mcq",
  LOGIN = "login",
  REGISTER = "register",
  FORGOT_PASSWORD = "forgot-password",
  SUPABASE_AUTH = "supabase-auth",
  QUESTION_PAPER = "question-paper",
  PREVIOUS_SUBMISSIONS = "pevious-submissions",
  PROFILE = "user-profile",
  MY_SUMBISSIONS = "my-submissions",
  SUBMISSION = "submissions",
  PRIVACY_POLICY = "privacy-policy",
  TERMS_OF_SERVICE = "terms-of-service",
  CONTACT_US = "contact-us",
  PRICING_PLAN = "pricing-plan",
  MY_TRANSACTIONS = "my-transactions",
}
