export enum paths {
  HOMEPAGE = "home",
  STREAM_SELECT = "streams",
  EXAMS = "exams",
  DISCRIPTIVE = "discriptive",
  MCQ = "mcq",
  LOGIN = "login",
  REGISTER = "register",
  FORGOT_PASSWORD = "forgot-password",
  SUPABASE_AUTH = "supabase-auth",
  QUESTION_PAPER = "question-paper",
  PREVIOUS_SOLUTIONS = "pevious-solutions",
  PROFILE = "profile",
  MY_SUMBISSIONS = "my-submissions",
}
