version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/backend/server"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "gomod"
    directory: "/backend/ai-service"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "gomod"
    directory: "/backend/common"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/client/web"
    schedule:
      interval: "weekly"
    target-branch: "dev"

  - package-ecosystem: "npm"
    directory: "/client/roadmap"
    schedule:
      interval: "weekly"
    target-branch: "dev"
