repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: "^backend/.*"
      - id: end-of-file-fixer
        files: "^backend/.*"
      - id: check-yaml
        files: "^backend/.*"
      - id: check-added-large-files
        files: "^backend/.*"
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
      - id: go-fmt
        files: "^backend/.*"
      - id: go-imports
        files: "^backend/.*"
      - id: no-go-testing
        files: "^backend/.*"
      - id: golangci-lint
        files: "^backend/.*"
      - id: go-unit-tests
        files: "^backend/.*"
