// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CachedQuestionMetadata is the predicate function for cachedquestionmetadata builders.
type CachedQuestionMetadata func(*sql.Selector)
