// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CachedQuestionMetaData is the predicate function for cachedquestionmetadata builders.
type CachedQuestionMetaData func(*sql.Selector)

// Exam is the predicate function for exam builders.
type Exam func(*sql.Selector)

// ExamCategory is the predicate function for examcategory builders.
type ExamCategory func(*sql.Selector)

// ExamSetting is the predicate function for examsetting builders.
type ExamSetting func(*sql.Selector)
