// Code generated by ent, DO NOT EDIT.

package ent

import (
	"common/ent/examattempt"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamAttemptCreate is the builder for creating a ExamAttempt entity.
type ExamAttemptCreate struct {
	config
	mutation *ExamAttemptMutation
	hooks    []Hook
}

// SetAttemptNumber sets the "attempt_number" field.
func (eac *ExamAttemptCreate) SetAttemptNumber(i int) *ExamAttemptCreate {
	eac.mutation.SetAttemptNumber(i)
	return eac
}

// SetCreatedAt sets the "created_at" field.
func (eac *ExamAttemptCreate) SetCreatedAt(t time.Time) *ExamAttemptCreate {
	eac.mutation.SetCreatedAt(t)
	return eac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (eac *ExamAttemptCreate) SetNillableCreatedAt(t *time.Time) *ExamAttemptCreate {
	if t != nil {
		eac.SetCreatedAt(*t)
	}
	return eac
}

// SetUpdatedAt sets the "updated_at" field.
func (eac *ExamAttemptCreate) SetUpdatedAt(t time.Time) *ExamAttemptCreate {
	eac.mutation.SetUpdatedAt(t)
	return eac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (eac *ExamAttemptCreate) SetNillableUpdatedAt(t *time.Time) *ExamAttemptCreate {
	if t != nil {
		eac.SetUpdatedAt(*t)
	}
	return eac
}

// Mutation returns the ExamAttemptMutation object of the builder.
func (eac *ExamAttemptCreate) Mutation() *ExamAttemptMutation {
	return eac.mutation
}

// Save creates the ExamAttempt in the database.
func (eac *ExamAttemptCreate) Save(ctx context.Context) (*ExamAttempt, error) {
	eac.defaults()
	return withHooks(ctx, eac.sqlSave, eac.mutation, eac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (eac *ExamAttemptCreate) SaveX(ctx context.Context) *ExamAttempt {
	v, err := eac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eac *ExamAttemptCreate) Exec(ctx context.Context) error {
	_, err := eac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eac *ExamAttemptCreate) ExecX(ctx context.Context) {
	if err := eac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eac *ExamAttemptCreate) defaults() {
	if _, ok := eac.mutation.CreatedAt(); !ok {
		v := examattempt.DefaultCreatedAt()
		eac.mutation.SetCreatedAt(v)
	}
	if _, ok := eac.mutation.UpdatedAt(); !ok {
		v := examattempt.DefaultUpdatedAt()
		eac.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eac *ExamAttemptCreate) check() error {
	if _, ok := eac.mutation.AttemptNumber(); !ok {
		return &ValidationError{Name: "attempt_number", err: errors.New(`ent: missing required field "ExamAttempt.attempt_number"`)}
	}
	if _, ok := eac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExamAttempt.created_at"`)}
	}
	if _, ok := eac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExamAttempt.updated_at"`)}
	}
	return nil
}

func (eac *ExamAttemptCreate) sqlSave(ctx context.Context) (*ExamAttempt, error) {
	if err := eac.check(); err != nil {
		return nil, err
	}
	_node, _spec := eac.createSpec()
	if err := sqlgraph.CreateNode(ctx, eac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	eac.mutation.id = &_node.ID
	eac.mutation.done = true
	return _node, nil
}

func (eac *ExamAttemptCreate) createSpec() (*ExamAttempt, *sqlgraph.CreateSpec) {
	var (
		_node = &ExamAttempt{config: eac.config}
		_spec = sqlgraph.NewCreateSpec(examattempt.Table, sqlgraph.NewFieldSpec(examattempt.FieldID, field.TypeInt))
	)
	if value, ok := eac.mutation.AttemptNumber(); ok {
		_spec.SetField(examattempt.FieldAttemptNumber, field.TypeInt, value)
		_node.AttemptNumber = value
	}
	if value, ok := eac.mutation.CreatedAt(); ok {
		_spec.SetField(examattempt.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := eac.mutation.UpdatedAt(); ok {
		_spec.SetField(examattempt.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ExamAttemptCreateBulk is the builder for creating many ExamAttempt entities in bulk.
type ExamAttemptCreateBulk struct {
	config
	err      error
	builders []*ExamAttemptCreate
}

// Save creates the ExamAttempt entities in the database.
func (eacb *ExamAttemptCreateBulk) Save(ctx context.Context) ([]*ExamAttempt, error) {
	if eacb.err != nil {
		return nil, eacb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(eacb.builders))
	nodes := make([]*ExamAttempt, len(eacb.builders))
	mutators := make([]Mutator, len(eacb.builders))
	for i := range eacb.builders {
		func(i int, root context.Context) {
			builder := eacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExamAttemptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, eacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, eacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, eacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (eacb *ExamAttemptCreateBulk) SaveX(ctx context.Context) []*ExamAttempt {
	v, err := eacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (eacb *ExamAttemptCreateBulk) Exec(ctx context.Context) error {
	_, err := eacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eacb *ExamAttemptCreateBulk) ExecX(ctx context.Context) {
	if err := eacb.Exec(ctx); err != nil {
		panic(err)
	}
}
