// Code generated by ent, DO NOT EDIT.

package ent

import (
	"common/ent/examcategory"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ExamCategory is the model entity for the ExamCategory schema.
type ExamCategory struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name examcategory.Name `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ExamCategoryQuery when eager-loading is set.
	Edges        ExamCategoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ExamCategoryEdges holds the relations/edges for other nodes in the graph.
type ExamCategoryEdges struct {
	// Exams holds the value of the exams edge.
	Exams []*Exam `json:"exams,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*ExamGroup `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ExamsOrErr returns the Exams value or an error if the edge
// was not loaded in eager-loading.
func (e ExamCategoryEdges) ExamsOrErr() ([]*Exam, error) {
	if e.loadedTypes[0] {
		return e.Exams, nil
	}
	return nil, &NotLoadedError{edge: "exams"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e ExamCategoryEdges) GroupsOrErr() ([]*ExamGroup, error) {
	if e.loadedTypes[1] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExamCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case examcategory.FieldIsActive:
			values[i] = new(sql.NullBool)
		case examcategory.FieldID:
			values[i] = new(sql.NullInt64)
		case examcategory.FieldName, examcategory.FieldDescription:
			values[i] = new(sql.NullString)
		case examcategory.FieldCreatedAt, examcategory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExamCategory fields.
func (ec *ExamCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case examcategory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ec.ID = int(value.Int64)
		case examcategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				ec.Name = examcategory.Name(value.String)
			}
		case examcategory.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ec.Description = value.String
			}
		case examcategory.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				ec.IsActive = value.Bool
			}
		case examcategory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ec.CreatedAt = value.Time
			}
		case examcategory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ec.UpdatedAt = value.Time
			}
		default:
			ec.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExamCategory.
// This includes values selected through modifiers, order, etc.
func (ec *ExamCategory) Value(name string) (ent.Value, error) {
	return ec.selectValues.Get(name)
}

// QueryExams queries the "exams" edge of the ExamCategory entity.
func (ec *ExamCategory) QueryExams() *ExamQuery {
	return NewExamCategoryClient(ec.config).QueryExams(ec)
}

// QueryGroups queries the "groups" edge of the ExamCategory entity.
func (ec *ExamCategory) QueryGroups() *ExamGroupQuery {
	return NewExamCategoryClient(ec.config).QueryGroups(ec)
}

// Update returns a builder for updating this ExamCategory.
// Note that you need to call ExamCategory.Unwrap() before calling this method if this ExamCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (ec *ExamCategory) Update() *ExamCategoryUpdateOne {
	return NewExamCategoryClient(ec.config).UpdateOne(ec)
}

// Unwrap unwraps the ExamCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ec *ExamCategory) Unwrap() *ExamCategory {
	_tx, ok := ec.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExamCategory is not a transactional entity")
	}
	ec.config.driver = _tx.drv
	return ec
}

// String implements the fmt.Stringer.
func (ec *ExamCategory) String() string {
	var builder strings.Builder
	builder.WriteString("ExamCategory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ec.ID))
	builder.WriteString("name=")
	builder.WriteString(fmt.Sprintf("%v", ec.Name))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ec.Description)
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", ec.IsActive))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ec.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ec.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ExamCategories is a parsable slice of ExamCategory.
type ExamCategories []*ExamCategory
