// Code generated by ent, DO NOT EDIT.

package ent

import (
	"common/ent/examassesment"
	"common/ent/examattempt"
	"common/ent/generatedexam"
	"common/ent/predicate"
	"common/ent/user"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ExamAttemptQuery is the builder for querying ExamAttempt entities.
type ExamAttemptQuery struct {
	config
	ctx               *QueryContext
	order             []examattempt.OrderOption
	inters            []Interceptor
	predicates        []predicate.ExamAttempt
	withGeneratedexam *GeneratedExamQuery
	withUser          *UserQuery
	withAssesment     *ExamAssesmentQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ExamAttemptQuery builder.
func (eaq *ExamAttemptQuery) Where(ps ...predicate.ExamAttempt) *ExamAttemptQuery {
	eaq.predicates = append(eaq.predicates, ps...)
	return eaq
}

// Limit the number of records to be returned by this query.
func (eaq *ExamAttemptQuery) Limit(limit int) *ExamAttemptQuery {
	eaq.ctx.Limit = &limit
	return eaq
}

// Offset to start from.
func (eaq *ExamAttemptQuery) Offset(offset int) *ExamAttemptQuery {
	eaq.ctx.Offset = &offset
	return eaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (eaq *ExamAttemptQuery) Unique(unique bool) *ExamAttemptQuery {
	eaq.ctx.Unique = &unique
	return eaq
}

// Order specifies how the records should be ordered.
func (eaq *ExamAttemptQuery) Order(o ...examattempt.OrderOption) *ExamAttemptQuery {
	eaq.order = append(eaq.order, o...)
	return eaq
}

// QueryGeneratedexam chains the current query on the "generatedexam" edge.
func (eaq *ExamAttemptQuery) QueryGeneratedexam() *GeneratedExamQuery {
	query := (&GeneratedExamClient{config: eaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(examattempt.Table, examattempt.FieldID, selector),
			sqlgraph.To(generatedexam.Table, generatedexam.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, examattempt.GeneratedexamTable, examattempt.GeneratedexamColumn),
		)
		fromU = sqlgraph.SetNeighbors(eaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (eaq *ExamAttemptQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: eaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(examattempt.Table, examattempt.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, examattempt.UserTable, examattempt.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(eaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAssesment chains the current query on the "assesment" edge.
func (eaq *ExamAttemptQuery) QueryAssesment() *ExamAssesmentQuery {
	query := (&ExamAssesmentClient{config: eaq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := eaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := eaq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(examattempt.Table, examattempt.FieldID, selector),
			sqlgraph.To(examassesment.Table, examassesment.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, examattempt.AssesmentTable, examattempt.AssesmentColumn),
		)
		fromU = sqlgraph.SetNeighbors(eaq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ExamAttempt entity from the query.
// Returns a *NotFoundError when no ExamAttempt was found.
func (eaq *ExamAttemptQuery) First(ctx context.Context) (*ExamAttempt, error) {
	nodes, err := eaq.Limit(1).All(setContextOp(ctx, eaq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{examattempt.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (eaq *ExamAttemptQuery) FirstX(ctx context.Context) *ExamAttempt {
	node, err := eaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ExamAttempt ID from the query.
// Returns a *NotFoundError when no ExamAttempt ID was found.
func (eaq *ExamAttemptQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eaq.Limit(1).IDs(setContextOp(ctx, eaq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{examattempt.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (eaq *ExamAttemptQuery) FirstIDX(ctx context.Context) int {
	id, err := eaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ExamAttempt entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ExamAttempt entity is found.
// Returns a *NotFoundError when no ExamAttempt entities are found.
func (eaq *ExamAttemptQuery) Only(ctx context.Context) (*ExamAttempt, error) {
	nodes, err := eaq.Limit(2).All(setContextOp(ctx, eaq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{examattempt.Label}
	default:
		return nil, &NotSingularError{examattempt.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (eaq *ExamAttemptQuery) OnlyX(ctx context.Context) *ExamAttempt {
	node, err := eaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ExamAttempt ID in the query.
// Returns a *NotSingularError when more than one ExamAttempt ID is found.
// Returns a *NotFoundError when no entities are found.
func (eaq *ExamAttemptQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = eaq.Limit(2).IDs(setContextOp(ctx, eaq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{examattempt.Label}
	default:
		err = &NotSingularError{examattempt.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (eaq *ExamAttemptQuery) OnlyIDX(ctx context.Context) int {
	id, err := eaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ExamAttempts.
func (eaq *ExamAttemptQuery) All(ctx context.Context) ([]*ExamAttempt, error) {
	ctx = setContextOp(ctx, eaq.ctx, ent.OpQueryAll)
	if err := eaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ExamAttempt, *ExamAttemptQuery]()
	return withInterceptors[[]*ExamAttempt](ctx, eaq, qr, eaq.inters)
}

// AllX is like All, but panics if an error occurs.
func (eaq *ExamAttemptQuery) AllX(ctx context.Context) []*ExamAttempt {
	nodes, err := eaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ExamAttempt IDs.
func (eaq *ExamAttemptQuery) IDs(ctx context.Context) (ids []int, err error) {
	if eaq.ctx.Unique == nil && eaq.path != nil {
		eaq.Unique(true)
	}
	ctx = setContextOp(ctx, eaq.ctx, ent.OpQueryIDs)
	if err = eaq.Select(examattempt.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (eaq *ExamAttemptQuery) IDsX(ctx context.Context) []int {
	ids, err := eaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (eaq *ExamAttemptQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, eaq.ctx, ent.OpQueryCount)
	if err := eaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, eaq, querierCount[*ExamAttemptQuery](), eaq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (eaq *ExamAttemptQuery) CountX(ctx context.Context) int {
	count, err := eaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (eaq *ExamAttemptQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, eaq.ctx, ent.OpQueryExist)
	switch _, err := eaq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (eaq *ExamAttemptQuery) ExistX(ctx context.Context) bool {
	exist, err := eaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ExamAttemptQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (eaq *ExamAttemptQuery) Clone() *ExamAttemptQuery {
	if eaq == nil {
		return nil
	}
	return &ExamAttemptQuery{
		config:            eaq.config,
		ctx:               eaq.ctx.Clone(),
		order:             append([]examattempt.OrderOption{}, eaq.order...),
		inters:            append([]Interceptor{}, eaq.inters...),
		predicates:        append([]predicate.ExamAttempt{}, eaq.predicates...),
		withGeneratedexam: eaq.withGeneratedexam.Clone(),
		withUser:          eaq.withUser.Clone(),
		withAssesment:     eaq.withAssesment.Clone(),
		// clone intermediate query.
		sql:  eaq.sql.Clone(),
		path: eaq.path,
	}
}

// WithGeneratedexam tells the query-builder to eager-load the nodes that are connected to
// the "generatedexam" edge. The optional arguments are used to configure the query builder of the edge.
func (eaq *ExamAttemptQuery) WithGeneratedexam(opts ...func(*GeneratedExamQuery)) *ExamAttemptQuery {
	query := (&GeneratedExamClient{config: eaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eaq.withGeneratedexam = query
	return eaq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (eaq *ExamAttemptQuery) WithUser(opts ...func(*UserQuery)) *ExamAttemptQuery {
	query := (&UserClient{config: eaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eaq.withUser = query
	return eaq
}

// WithAssesment tells the query-builder to eager-load the nodes that are connected to
// the "assesment" edge. The optional arguments are used to configure the query builder of the edge.
func (eaq *ExamAttemptQuery) WithAssesment(opts ...func(*ExamAssesmentQuery)) *ExamAttemptQuery {
	query := (&ExamAssesmentClient{config: eaq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	eaq.withAssesment = query
	return eaq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AttemptNumber int `json:"attempt_number,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ExamAttempt.Query().
//		GroupBy(examattempt.FieldAttemptNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (eaq *ExamAttemptQuery) GroupBy(field string, fields ...string) *ExamAttemptGroupBy {
	eaq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ExamAttemptGroupBy{build: eaq}
	grbuild.flds = &eaq.ctx.Fields
	grbuild.label = examattempt.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AttemptNumber int `json:"attempt_number,omitempty"`
//	}
//
//	client.ExamAttempt.Query().
//		Select(examattempt.FieldAttemptNumber).
//		Scan(ctx, &v)
func (eaq *ExamAttemptQuery) Select(fields ...string) *ExamAttemptSelect {
	eaq.ctx.Fields = append(eaq.ctx.Fields, fields...)
	sbuild := &ExamAttemptSelect{ExamAttemptQuery: eaq}
	sbuild.label = examattempt.Label
	sbuild.flds, sbuild.scan = &eaq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ExamAttemptSelect configured with the given aggregations.
func (eaq *ExamAttemptQuery) Aggregate(fns ...AggregateFunc) *ExamAttemptSelect {
	return eaq.Select().Aggregate(fns...)
}

func (eaq *ExamAttemptQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range eaq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, eaq); err != nil {
				return err
			}
		}
	}
	for _, f := range eaq.ctx.Fields {
		if !examattempt.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if eaq.path != nil {
		prev, err := eaq.path(ctx)
		if err != nil {
			return err
		}
		eaq.sql = prev
	}
	return nil
}

func (eaq *ExamAttemptQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ExamAttempt, error) {
	var (
		nodes       = []*ExamAttempt{}
		withFKs     = eaq.withFKs
		_spec       = eaq.querySpec()
		loadedTypes = [3]bool{
			eaq.withGeneratedexam != nil,
			eaq.withUser != nil,
			eaq.withAssesment != nil,
		}
	)
	if eaq.withGeneratedexam != nil || eaq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, examattempt.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ExamAttempt).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ExamAttempt{config: eaq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, eaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := eaq.withGeneratedexam; query != nil {
		if err := eaq.loadGeneratedexam(ctx, query, nodes, nil,
			func(n *ExamAttempt, e *GeneratedExam) { n.Edges.Generatedexam = e }); err != nil {
			return nil, err
		}
	}
	if query := eaq.withUser; query != nil {
		if err := eaq.loadUser(ctx, query, nodes, nil,
			func(n *ExamAttempt, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := eaq.withAssesment; query != nil {
		if err := eaq.loadAssesment(ctx, query, nodes, nil,
			func(n *ExamAttempt, e *ExamAssesment) { n.Edges.Assesment = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (eaq *ExamAttemptQuery) loadGeneratedexam(ctx context.Context, query *GeneratedExamQuery, nodes []*ExamAttempt, init func(*ExamAttempt), assign func(*ExamAttempt, *GeneratedExam)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ExamAttempt)
	for i := range nodes {
		if nodes[i].generated_exam_attempts == nil {
			continue
		}
		fk := *nodes[i].generated_exam_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(generatedexam.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "generated_exam_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (eaq *ExamAttemptQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ExamAttempt, init func(*ExamAttempt), assign func(*ExamAttempt, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ExamAttempt)
	for i := range nodes {
		if nodes[i].user_attempts == nil {
			continue
		}
		fk := *nodes[i].user_attempts
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_attempts" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (eaq *ExamAttemptQuery) loadAssesment(ctx context.Context, query *ExamAssesmentQuery, nodes []*ExamAttempt, init func(*ExamAttempt), assign func(*ExamAttempt, *ExamAssesment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ExamAttempt)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.ExamAssesment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(examattempt.AssesmentColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.exam_attempt_assesment
		if fk == nil {
			return fmt.Errorf(`foreign-key "exam_attempt_assesment" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "exam_attempt_assesment" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (eaq *ExamAttemptQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := eaq.querySpec()
	_spec.Node.Columns = eaq.ctx.Fields
	if len(eaq.ctx.Fields) > 0 {
		_spec.Unique = eaq.ctx.Unique != nil && *eaq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, eaq.driver, _spec)
}

func (eaq *ExamAttemptQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(examattempt.Table, examattempt.Columns, sqlgraph.NewFieldSpec(examattempt.FieldID, field.TypeInt))
	_spec.From = eaq.sql
	if unique := eaq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if eaq.path != nil {
		_spec.Unique = true
	}
	if fields := eaq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, examattempt.FieldID)
		for i := range fields {
			if fields[i] != examattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := eaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := eaq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := eaq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := eaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (eaq *ExamAttemptQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(eaq.driver.Dialect())
	t1 := builder.Table(examattempt.Table)
	columns := eaq.ctx.Fields
	if len(columns) == 0 {
		columns = examattempt.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if eaq.sql != nil {
		selector = eaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if eaq.ctx.Unique != nil && *eaq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range eaq.predicates {
		p(selector)
	}
	for _, p := range eaq.order {
		p(selector)
	}
	if offset := eaq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := eaq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ExamAttemptGroupBy is the group-by builder for ExamAttempt entities.
type ExamAttemptGroupBy struct {
	selector
	build *ExamAttemptQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (eagb *ExamAttemptGroupBy) Aggregate(fns ...AggregateFunc) *ExamAttemptGroupBy {
	eagb.fns = append(eagb.fns, fns...)
	return eagb
}

// Scan applies the selector query and scans the result into the given value.
func (eagb *ExamAttemptGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eagb.build.ctx, ent.OpQueryGroupBy)
	if err := eagb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExamAttemptQuery, *ExamAttemptGroupBy](ctx, eagb.build, eagb, eagb.build.inters, v)
}

func (eagb *ExamAttemptGroupBy) sqlScan(ctx context.Context, root *ExamAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(eagb.fns))
	for _, fn := range eagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*eagb.flds)+len(eagb.fns))
		for _, f := range *eagb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*eagb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eagb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ExamAttemptSelect is the builder for selecting fields of ExamAttempt entities.
type ExamAttemptSelect struct {
	*ExamAttemptQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (eas *ExamAttemptSelect) Aggregate(fns ...AggregateFunc) *ExamAttemptSelect {
	eas.fns = append(eas.fns, fns...)
	return eas
}

// Scan applies the selector query and scans the result into the given value.
func (eas *ExamAttemptSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, eas.ctx, ent.OpQuerySelect)
	if err := eas.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ExamAttemptQuery, *ExamAttemptSelect](ctx, eas.ExamAttemptQuery, eas, eas.inters, v)
}

func (eas *ExamAttemptSelect) sqlScan(ctx context.Context, root *ExamAttemptQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(eas.fns))
	for _, fn := range eas.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*eas.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := eas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
