// Code generated by ent, DO NOT EDIT.

package ent

import (
	"common/ent/examresult"
	"common/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamResultUpdate is the builder for updating ExamResult entities.
type ExamResultUpdate struct {
	config
	hooks    []Hook
	mutation *ExamResultMutation
}

// Where appends a list predicates to the ExamResultUpdate builder.
func (eru *ExamResultUpdate) Where(ps ...predicate.ExamResult) *ExamResultUpdate {
	eru.mutation.Where(ps...)
	return eru
}

// Mutation returns the ExamResultMutation object of the builder.
func (eru *ExamResultUpdate) Mutation() *ExamResultMutation {
	return eru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eru *ExamResultUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eru.sqlSave, eru.mutation, eru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eru *ExamResultUpdate) SaveX(ctx context.Context) int {
	affected, err := eru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eru *ExamResultUpdate) Exec(ctx context.Context) error {
	_, err := eru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eru *ExamResultUpdate) ExecX(ctx context.Context) {
	if err := eru.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eru *ExamResultUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(examresult.Table, examresult.Columns, sqlgraph.NewFieldSpec(examresult.FieldID, field.TypeInt))
	if ps := eru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{examresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eru.mutation.done = true
	return n, nil
}

// ExamResultUpdateOne is the builder for updating a single ExamResult entity.
type ExamResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExamResultMutation
}

// Mutation returns the ExamResultMutation object of the builder.
func (eruo *ExamResultUpdateOne) Mutation() *ExamResultMutation {
	return eruo.mutation
}

// Where appends a list predicates to the ExamResultUpdate builder.
func (eruo *ExamResultUpdateOne) Where(ps ...predicate.ExamResult) *ExamResultUpdateOne {
	eruo.mutation.Where(ps...)
	return eruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (eruo *ExamResultUpdateOne) Select(field string, fields ...string) *ExamResultUpdateOne {
	eruo.fields = append([]string{field}, fields...)
	return eruo
}

// Save executes the query and returns the updated ExamResult entity.
func (eruo *ExamResultUpdateOne) Save(ctx context.Context) (*ExamResult, error) {
	return withHooks(ctx, eruo.sqlSave, eruo.mutation, eruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eruo *ExamResultUpdateOne) SaveX(ctx context.Context) *ExamResult {
	node, err := eruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (eruo *ExamResultUpdateOne) Exec(ctx context.Context) error {
	_, err := eruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eruo *ExamResultUpdateOne) ExecX(ctx context.Context) {
	if err := eruo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (eruo *ExamResultUpdateOne) sqlSave(ctx context.Context) (_node *ExamResult, err error) {
	_spec := sqlgraph.NewUpdateSpec(examresult.Table, examresult.Columns, sqlgraph.NewFieldSpec(examresult.FieldID, field.TypeInt))
	id, ok := eruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ExamResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := eruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, examresult.FieldID)
		for _, f := range fields {
			if !examresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != examresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := eruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ExamResult{config: eruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, eruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{examresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	eruo.mutation.done = true
	return _node, nil
}
