// Code generated by ent, DO NOT EDIT.

package ent

import (
	"common/ent/exam"
	"common/ent/subscription"
	"common/ent/subscriptionexam"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SubscriptionExam is the model entity for the SubscriptionExam schema.
type SubscriptionExam struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubscriptionExamQuery when eager-loading is set.
	Edges              SubscriptionExamEdges `json:"edges"`
	exam_subscriptions *int
	subscription_exams *int
	selectValues       sql.SelectValues
}

// SubscriptionExamEdges holds the relations/edges for other nodes in the graph.
type SubscriptionExamEdges struct {
	// Subscription holds the value of the subscription edge.
	Subscription *Subscription `json:"subscription,omitempty"`
	// Exam holds the value of the exam edge.
	Exam *Exam `json:"exam,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionExamEdges) SubscriptionOrErr() (*Subscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: subscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// ExamOrErr returns the Exam value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubscriptionExamEdges) ExamOrErr() (*Exam, error) {
	if e.Exam != nil {
		return e.Exam, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: exam.Label}
	}
	return nil, &NotLoadedError{edge: "exam"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubscriptionExam) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subscriptionexam.FieldID:
			values[i] = new(sql.NullInt64)
		case subscriptionexam.FieldCreatedAt, subscriptionexam.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case subscriptionexam.ForeignKeys[0]: // exam_subscriptions
			values[i] = new(sql.NullInt64)
		case subscriptionexam.ForeignKeys[1]: // subscription_exams
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubscriptionExam fields.
func (se *SubscriptionExam) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subscriptionexam.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			se.ID = int(value.Int64)
		case subscriptionexam.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				se.CreatedAt = value.Time
			}
		case subscriptionexam.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				se.UpdatedAt = value.Time
			}
		case subscriptionexam.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field exam_subscriptions", value)
			} else if value.Valid {
				se.exam_subscriptions = new(int)
				*se.exam_subscriptions = int(value.Int64)
			}
		case subscriptionexam.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field subscription_exams", value)
			} else if value.Valid {
				se.subscription_exams = new(int)
				*se.subscription_exams = int(value.Int64)
			}
		default:
			se.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SubscriptionExam.
// This includes values selected through modifiers, order, etc.
func (se *SubscriptionExam) Value(name string) (ent.Value, error) {
	return se.selectValues.Get(name)
}

// QuerySubscription queries the "subscription" edge of the SubscriptionExam entity.
func (se *SubscriptionExam) QuerySubscription() *SubscriptionQuery {
	return NewSubscriptionExamClient(se.config).QuerySubscription(se)
}

// QueryExam queries the "exam" edge of the SubscriptionExam entity.
func (se *SubscriptionExam) QueryExam() *ExamQuery {
	return NewSubscriptionExamClient(se.config).QueryExam(se)
}

// Update returns a builder for updating this SubscriptionExam.
// Note that you need to call SubscriptionExam.Unwrap() before calling this method if this SubscriptionExam
// was returned from a transaction, and the transaction was committed or rolled back.
func (se *SubscriptionExam) Update() *SubscriptionExamUpdateOne {
	return NewSubscriptionExamClient(se.config).UpdateOne(se)
}

// Unwrap unwraps the SubscriptionExam entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (se *SubscriptionExam) Unwrap() *SubscriptionExam {
	_tx, ok := se.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubscriptionExam is not a transactional entity")
	}
	se.config.driver = _tx.drv
	return se
}

// String implements the fmt.Stringer.
func (se *SubscriptionExam) String() string {
	var builder strings.Builder
	builder.WriteString("SubscriptionExam(")
	builder.WriteString(fmt.Sprintf("id=%v, ", se.ID))
	builder.WriteString("created_at=")
	builder.WriteString(se.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(se.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubscriptionExams is a parsable slice of SubscriptionExam.
type SubscriptionExams []*SubscriptionExam
