// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"common/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// ProviderSubscriptionID applies equality check predicate on the "provider_subscription_id" field. It's identical to ProviderSubscriptionIDEQ.
func ProviderSubscriptionID(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldProviderSubscriptionID, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPrice, v))
}

// DurationInMonths applies equality check predicate on the "duration_in_months" field. It's identical to DurationInMonthsEQ.
func DurationInMonths(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldDurationInMonths, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldIsActive, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldName, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderSubscriptionIDEQ applies the EQ predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDNEQ applies the NEQ predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDIn applies the In predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldProviderSubscriptionID, vs...))
}

// ProviderSubscriptionIDNotIn applies the NotIn predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldProviderSubscriptionID, vs...))
}

// ProviderSubscriptionIDGT applies the GT predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDGTE applies the GTE predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDLT applies the LT predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDLTE applies the LTE predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDContains applies the Contains predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDHasPrefix applies the HasPrefix predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDHasSuffix applies the HasSuffix predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDEqualFold applies the EqualFold predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldProviderSubscriptionID, v))
}

// ProviderSubscriptionIDContainsFold applies the ContainsFold predicate on the "provider_subscription_id" field.
func ProviderSubscriptionIDContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldProviderSubscriptionID, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...int) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v int) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldPrice, v))
}

// DurationInMonthsEQ applies the EQ predicate on the "duration_in_months" field.
func DurationInMonthsEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldDurationInMonths, v))
}

// DurationInMonthsNEQ applies the NEQ predicate on the "duration_in_months" field.
func DurationInMonthsNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldDurationInMonths, v))
}

// DurationInMonthsIn applies the In predicate on the "duration_in_months" field.
func DurationInMonthsIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldDurationInMonths, vs...))
}

// DurationInMonthsNotIn applies the NotIn predicate on the "duration_in_months" field.
func DurationInMonthsNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldDurationInMonths, vs...))
}

// DurationInMonthsGT applies the GT predicate on the "duration_in_months" field.
func DurationInMonthsGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldDurationInMonths, v))
}

// DurationInMonthsGTE applies the GTE predicate on the "duration_in_months" field.
func DurationInMonthsGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldDurationInMonths, v))
}

// DurationInMonthsLT applies the LT predicate on the "duration_in_months" field.
func DurationInMonthsLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldDurationInMonths, v))
}

// DurationInMonthsLTE applies the LTE predicate on the "duration_in_months" field.
func DurationInMonthsLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldDurationInMonths, v))
}

// DurationInMonthsContains applies the Contains predicate on the "duration_in_months" field.
func DurationInMonthsContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldDurationInMonths, v))
}

// DurationInMonthsHasPrefix applies the HasPrefix predicate on the "duration_in_months" field.
func DurationInMonthsHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldDurationInMonths, v))
}

// DurationInMonthsHasSuffix applies the HasSuffix predicate on the "duration_in_months" field.
func DurationInMonthsHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldDurationInMonths, v))
}

// DurationInMonthsEqualFold applies the EqualFold predicate on the "duration_in_months" field.
func DurationInMonthsEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldDurationInMonths, v))
}

// DurationInMonthsContainsFold applies the ContainsFold predicate on the "duration_in_months" field.
func DurationInMonthsContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldDurationInMonths, v))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldIsActive, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v bool) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldName, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasExams applies the HasEdge predicate on the "exams" edge.
func HasExams() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ExamsTable, ExamsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasExamsWith applies the HasEdge predicate on the "exams" edge with a given conditions (other predicates).
func HasExamsWith(preds ...predicate.SubscriptionExam) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newExamsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUserSubscriptions applies the HasEdge predicate on the "user_subscriptions" edge.
func HasUserSubscriptions() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UserSubscriptionsTable, UserSubscriptionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserSubscriptionsWith applies the HasEdge predicate on the "user_subscriptions" edge with a given conditions (other predicates).
func HasUserSubscriptionsWith(preds ...predicate.UserSubscription) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newUserSubscriptionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
