// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CachedQuestionMetadataColumns holds the columns for the "cached_question_metadata" table.
	CachedQuestionMetadataColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeString},
		{Name: "subject", Type: field.TypeString},
		{Name: "exam", Type: field.TypeString},
		{Name: "is_processed", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CachedQuestionMetadataTable holds the schema information for the "cached_question_metadata" table.
	CachedQuestionMetadataTable = &schema.Table{
		Name:       "cached_question_metadata",
		Columns:    CachedQuestionMetadataColumns,
		PrimaryKey: []*schema.Column{CachedQuestionMetadataColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CachedQuestionMetadataTable,
	}
)

func init() {
}
