name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0" # Specify the Go version you want to use

      - name: Install dependencies and run tests
        working-directory: backend
        run: |
          cd server
          go mod tidy
          go test -coverprofile=server-coverage.out ./...
          cd ../ai-service
          go mod tidy
          go test -coverprofile=ai-service-coverage.out ./...
          cd ../common
          go mod tidy
          go test -coverprofile=common-coverage.out ./...
          echo "Combining coverage reports"
          cat server/server-coverage.out ai-service/ai-service-coverage.out common/common-coverage.out > combined-coverage.out
          go tool cover -func=combined-coverage.out -o lcov.info

      - name: Report LCOV coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./backend/lcov.info
