name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"

      - name: Install dependencies and Run tests
        run: |
          cd server && go mod tidy && go test -coverprofile=server-coverage.out ./...
          cd ../ai-service && go mod tidy && go test -coverprofile=ai-service-coverage.out ./...
          cd ../common && go mod tidy && go test -coverprofile=common-coverage.out ./...

      - name: Generate LCOV report for Server
        run: gcov2lcov -infile=server-coverage.out -outfile=server-lcov.info
        working-directory: backend/server

      - name: Generate LCOV report for AI Service
        run: gcov2lcov -infile=ai-service-coverage.out -outfile=ai-service-lcov.info
        working-directory: backend/ai-service

      - name: Generate LCOV report for Common
        run: gcov2lcov -infile=common-coverage.out -outfile=common-lcov.info
        working-directory: backend/common

      - name: Post Coverage Comment for Server
        run: |
          coverage=$(grep -Po '^\S+\s+\S+\s+\S+\s+\S+\s+\K\S+' server/server-lcov.info)
          echo "Server Coverage: $coverage%" > server-coverage-summary.txt
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"body":"'"$(<server-coverage-summary.txt)"'"}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      - name: Post Coverage Comment for AI Service
        run: |
          coverage=$(grep -Po '^\S+\s+\S+\s+\S+\s+\S+\s+\K\S+' ai-service/ai-service-lcov.info)
          echo "AI Service Coverage: $coverage%" > ai-service-coverage-summary.txt
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"body":"'"$(<ai-service-coverage-summary.txt)"'"}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"

      - name: Post Coverage Comment for Common
        run: |
          coverage=$(grep -Po '^\S+\s+\S+\s+\S+\s+\S+\s+\K\S+' common/common-lcov.info)
          echo "Common Coverage: $coverage%" > common-coverage-summary.txt
          curl -s -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Content-Type: application/json" -d '{"body":"'"$(<common-coverage-summary.txt)"'"}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
