name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"

      # Run tests in backend/server
      - name: Install dependencies for server
        run: go mod tidy
        working-directory: "backend/server"

      - name: Run tests for server
        run: go test ./... -v
        working-directory: "backend/server"

      # Run tests in backend/ai-service
      - name: Install dependencies for ai-service
        run: go mod tidy
        working-directory: "backend/ai-service"

      - name: Run tests for ai-service
        run: go test ./... -v
        working-directory: "backend/ai-service"

      # Run tests in backend/common
      - name: Install dependencies for common
        run: go mod tidy
        working-directory: "backend/common"

      - name: Run tests for common
        run: go test ./... -v
        working-directory: "backend/common"

      # Optionally report coverage for all services
      - name: Report coverage for server
        run: go test -cover ./...
        working-directory: "backend/server"

      - name: Report coverage for ai-service
        run: go test -cover ./...
        working-directory: "backend/ai-service"

      - name: Report coverage for common
        run: go test -cover ./...
        working-directory: "backend/common"
