name: Backend Unit Tests

on:
  pull_request:
    paths:
      - "backend/**"
      - ".github/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"

      - name: Install gocover-cobertura
        run: go install github.com/t-yuki/gocover-cobertura@latest

      - name: Install dependencies and Run tests
        run: |
          cd server && go mod tidy && go test -coverprofile=server-coverage.out ./...
          cd ../ai-service && go mod tidy && go test -coverprofile=ai-service-coverage.out ./...
          cd ../common && go mod tidy && go test -coverprofile=common-coverage.out ./...

      - name: Generate Cobertura Coverage Report for Server
        run: cat server/server-coverage.out | gocover-cobertura > server/coverage.xml
        working-directory: backend

      - name: Generate Cobertura Coverage Report for AI Service
        run: cat ai-service/ai-service-coverage.out | gocover-cobertura > ai-service/coverage.xml
        working-directory: backend

      - name: Generate Cobertura Coverage Report for Common
        run: cat common/common-coverage.out | gocover-cobertura > common/coverage.xml
        working-directory: backend

      # Use the Code Coverage Summary action to generate a summary and optionally fail the check if coverage is below threshold
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        continue-on-error: true
        with:
          filename: backend/**/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "0 100"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
