name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"

      # Run tests and collect coverage in backend/server
      - name: Run tests for server
        run: |
          cd backend/server
          go mod tidy
          go test -coverprofile=coverage.out ./...
        working-directory: "backend/server"

      # Run tests and collect coverage in backend/ai-service
      - name: Run tests for ai-service
        run: |
          cd backend/ai-service
          go mod tidy
          go test -coverprofile=coverage.out ./...
        working-directory: "backend/ai-service"

      # Run tests and collect coverage in backend/common
      - name: Run tests for common
        run: |
          cd backend/common
          go mod tidy
          go test -coverprofile=coverage.out ./...
        working-directory: "backend/common"

      # Generate coverage summary
      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: |
            backend/server/coverage.out
            backend/ai-service/coverage.out
            backend/common/coverage.out
