name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0" # Specify the Go version you want to use

      - name: Install LCOV
        run: sudo apt-get install lcov

      - name: Run tests in ai-service
        run: |
          cd backend/ai-service
          go mod tidy
          go test -coverprofile=ai-service-coverage.out ./...

      - name: Run tests in common
        run: |
          cd backend/common
          go mod tidy
          go test -coverprofile=common-coverage.out ./...

      - name: Run tests in server
        run: |
          cd backend/server
          go mod tidy
          go test -coverprofile=server-coverage.out ./...

      - name: Combine coverage reports
        run: |
          echo "Combining coverage reports"
          cat backend/ai-service/ai-service-coverage.out backend/common/common-coverage.out backend/server/server-coverage.out > backend/combined-coverage.out

      - name: Generate LCOV report
        run: |
          genhtml -o coverage-report backend/combined-coverage.out --output-directory coverage-report

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage-report
