name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0" # Specify the Go version you want to use

      - name: Install Goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Run tests and collect coverage
        run: |
          cd backend/server
          go mod tidy
          go test -coverprofile=coverage.out ./...
          cd ../ai-service
          go mod tidy
          go test -coverprofile=coverage.out ./...
          cd ../common
          go mod tidy
          go test -coverprofile=coverage.out ./...

      - name: Upload coverage to Codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

      - name: Combine coverage reports
        run: |
          goveralls -service=github -coverprofile=coverage.out -repotoken ${{ secrets.GITHUB_TOKEN }}

      - name: Upload coverage report
        uses: actions/upload-artifact@v3 # Updated to v3
        with:
          name: coverage-report
          path: |
            backend/server/coverage.out
            backend/ai-service/coverage.out
            backend/common/coverage.out

      - name: Code Coverage Summary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: |
            backend/server/coverage.out
            backend/ai-service/coverage.out
            backend/common/coverage.out

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
