name: Backend Unit Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

  pull_request:
    branches:
      - main
      - dev
    paths:
      - "backend/**"
      - ".github/**"

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  run_backend_unit_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23.0"

      - name: Install dependencies and Run tests
        run: |
          cd server && go mod tidy && go test -coverprofile=server-coverage.out ./...
          cd ../ai-service && go mod tidy && go test -coverprofile=ai-service-coverage.out ./...
          cd ../common && go mod tidy && go test -coverprofile=common-coverage.out ./...

      - name: Generate LCOV report for Server
        run: go tool cover -func=server-coverage.out -o server-lcov.info
        working-directory: backend/server

      - name: Display LCOV report content
        run: cat server-lcov.info
        working-directory: backend/server

      # - name: Generate LCOV report for AI Service
      #   run: go tool cover -func=ai-service-coverage.out -o ai-service-lcov.info
      #   working-directory: backend/ai-service

      # - name: Generate LCOV report for Common
      #   run: go tool cover -func=common-coverage.out -o common-lcov.info
      #   working-directory: backend/common

      # - name: Post Coverage Comment for Server
      #   uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: backend/server/server-lcov.info

      # - name: Post Coverage Comment for AI Service
      #   uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: backend/ai-service/ai-service-lcov.info

      # - name: Post Coverage Comment for Common
      #   uses: romeovs/lcov-reporter-action@v0.2.16
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     lcov-file: backend/common/common-lcov.info
