name: golangci-lint

on:
  pull_request:
  push:
    branches:
      - "main"
      - "dev"
    paths:
      - "backend/**"
      - ".github/**"

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  detect-modules:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: set-modules
        run: |
          # Detect Go modules in both ai-service and server
          modules=$(find backend/ai-service backend/server backend/common -name 'go.mod' -exec dirname {} \;)
          echo "modules=$(echo "$modules" | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT

  golangci-lint:
    needs: detect-modules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-modules.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run golangci-lint on ${{ matrix.module }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.module }}
          args: "--timeout 5m --fix -v"
